### ISSUE TITLE
[1.4 alpha] Exception when trying to open bags

### ISSUE THREAD

**Issue by gosvoh** [Fargowilta/Fargowiltas#127]
```c#
System.MissingMethodException: Method not found: 'Void Terraria.Player.QuickSpawnItem(Int32, Int32)'.
   at Fargowiltas.Items.FargoGlobalItem.OpenVanillaBag(String context, Player player, Int32 arg)
   at Terraria.ModLoader.ItemLoader.OpenVanillaBag(String context, Player player, Int32 arg) in tModLoader\Terraria\ModLoader\ItemLoader.cs:line 1139
   at Terraria.Player.OpenBossBag(Int32 type) in tModLoader\Terraria\Player.cs:line 4057
   at Terraria.UI.ItemSlot.RightClick_FindSpecialActions(Item[] inv, Int32 context, Int32 slot, Player player) in tModLoader\Terraria\UI\ItemSlot.cs:line 1059
   at Terraria.UI.ItemSlot.RightClick(Item[] inv, Int32 context, Int32 slot) in tModLoader\Terraria\UI\ItemSlot.cs:line 983
   at Terraria.Main.DrawInventory() in tModLoader\Terraria\Main.cs:line 30326
   at Terraria.Main.DrawInterface_27_Inventory() in tModLoader\Terraria\Main.cs:line 34152
   at Terraria.Main.<SetupDrawInterfaceLayers>b__1571_24() in tModLoader\Terraria\Main.cs:line 33645
   at Terraria.UI.LegacyGameInterfaceLayer.DrawSelf() in tModLoader\Terraria\UI\LegacyGameInterfaceLayer.cs:line 12
   at Terraria.UI.GameInterfaceLayer.Draw() in tModLoader\Terraria\UI\GameInterfaceLayer.cs:line 41
   at Terraria.Main.DrawInterface(GameTime gameTime) in tModLoader\Terraria\Main.cs:line 33717
   at Terraria.Main.DoDraw(GameTime gameTime) in tModLoader\Terraria\Main.cs:line 48455
   at Terraria.Main.Draw(GameTime gameTime) in tModLoader\Terraria\Main.cs:line 47697
   at Microsoft.Xna.Framework.Game.Tick() in D:\a\tModLoader\tModLoader\FNA\src\Game.cs:line 559
   at Microsoft.Xna.Framework.Game.RunLoop() in D:\a\tModLoader\tModLoader\FNA\src\Game.cs:line 880
   at Microsoft.Xna.Framework.Game.Run() in D:\a\tModLoader\tModLoader\FNA\src\Game.cs:line 415
   at Terraria.Program.LaunchGame_(Boolean isServer) in tModLoader\Terraria\Program.cs:line 207
   at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs) in tModLoader\Terraria\Program.cs:line 173
   at MonoLaunch.Main(String[] args) in tModLoader\Terraria\MonoLaunch.cs:line 52
```

**Comment by gosvoh** [comment]
Fixed in the latest update, thank you
