### ISSUE TITLE
Tmodloader had another arbitrary update.

### ISSUE THREAD

**Issue by George0079** [Fargowilta/Fargowiltas#135]
Tmodloader is saying it's on 6.96.4. Don't know what arbitrary change they did this time, and I'm guessing you're already working on it, but this is more for the people trying to figure out if the problem is on their end or not.

**Comment by NWrenger** [comment]
Now a I have the same Issue. The log:
[22:35:46.230] [.NET ThreadPool Worker/ERROR] [tML]: An error occurred while loading Fargowiltas v2.8.2
It has been detected that this mod was built for tModLoader v2022.6.96.1
However, you are using tModLoader v2022.7.58.4
The mod will need to be updated to match the current tModLoader version, or may be incompatible with the version of some of your other mods. Click the 'Open Web Help' button to learn more.
The mod(s) have been automatically disabled.
Terraria.ModLoader.Exceptions.JITException: 
In Fargowiltas.FargoGlobalRecipe.RecipeAvailable, Method not found: 'Boolean Terraria.ModLoader.GlobalRecipe.RecipeAvailable(Terraria.Recipe)'.

   at Terraria.ModLoader.Core.AssemblyManager.JITAssemblies(IEnumerable`1 assemblies, PreJITFilter filter) in tModLoader\Terraria\ModLoader\Core\AssemblyManager.cs:line 378
   at Terraria.ModLoader.Core.AssemblyManager.JITMod(Mod mod) in tModLoader\Terraria\ModLoader\Core\AssemblyManager.cs:line 336
   at Terraria.ModLoader.ModContent.<>c.<Load>b__42_0(Mod mod) in tModLoader\Terraria\ModLoader\ModContent.cs:line 311
   at Terraria.ModLoader.ModContent.LoadModContent(CancellationToken token, Action`1 loadAction) in tModLoader\Terraria\ModLoader\ModContent.cs:line 382
   at Terraria.ModLoader.ModContent.Load(CancellationToken token) in tModLoader\Terraria\ModLoader\ModContent.cs:line 310
   at Terraria.ModLoader.ModLoader.Load(CancellationToken token) in tModLoader\Terraria\ModLoader\ModLoader.cs:line 124
[22:35:46.231] [.NET ThreadPool Worker/INFO] [tML]: Disabling Mod: Fargowiltas
